# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            set -x

            pip install --user codecov
            cp .env.example .env

            docker-compose pull
            docker-compose build

      # run tests!
      - run:
          name: run tests
          command: |
            set -x

            docker-compose up -d
            docker-compose ps

            docker-compose run --rm wsgi tools/ci/run.sh initdb
            docker-compose run --rm wsgi tools/ci/run.sh test -v --cov=huskar_api tests/

            python -m codecov

      - store_artifacts:
          path: test-reports
          destination: test-reports
